development:
  adapter: postgresql
  database: MHbackend_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: MHbackend_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: MHbackend_production
  pool: 5
  timeout: 5000
